runtime: python311

instance_class: F2

env_variables:
  DATABASE_URL: "sqlite:///./novamailer.db"
  SECRET_KEY: "your-secret-key-change-in-production"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ALGORITHM: "HS256"

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
